name: kaspium_wallet
description: The Ultimate Self-Custodial Wallet for the Kaspa Network.
publish_to: "none"

version: 1.0.1+12

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Components
  qr_flutter: 4.1.0
  qr_code_scanner: 1.0.1
  auto_size_text: 3.0.0
  flutter_slidable: 3.0.0
  flutter_displaymode: 0.6.0
  image_picker: 0.8.7+5
  barcode_finder: 0.0.5
  flutter_portal: 1.1.4

  # Network and HTTP
  http: 0.13.6
  grpc: 3.2.0

  # Data Management
  flutter_secure_storage: 8.0.0
  shared_preferences: 2.1.1
  hive_flutter: 1.1.0
  path_provider: 2.0.15

  # Device and System Information
  package_info_plus: 4.0.0
  device_info_plus: 9.0.0

  # Localization and Formatting
  json_annotation: 4.8.1
  intl: 0.18.1
  decimal: 2.3.3

  # Logging and Debugging
  logger: 1.3.0

  # Authentication and Security
  local_auth: 2.1.6

  # Sharing and Interactions
  share_plus: 7.0.0
  url_launcher: 6.1.11

  # File Handling
  file_picker: 5.3.0

  # Miscellaneous Utilities
  app_links: 3.4.3
  flutter_vibrate: 1.3.0
  validators: 3.0.0
  cupertino_icons: 1.0.5
  oktoast: 3.3.1
  automatic_animated_list: 1.1.0
  lazy_load_scrollview: 1.3.0
  cross_file: 0.3.3+4
  protobuf: 2.1.0
  coinslib: 3.1.7
  collection: ^1.18.0
  fixnum: 1.1.0
  pointycastle: 3.7.3
  fast_immutable_collections: 9.1.1 # Bu satır eklendi

  # State Management
  flutter_riverpod: 2.3.6
  hooks_riverpod: 2.3.6
  flutter_hooks: 0.18.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.4
  json_serializable: 6.6.2
  flutter_lints: 2.0.1
  freezed: 2.3.4
  flutter_launcher_icons: 0.13.1
  watcher: 1.1.0

# Flutter launcher icons
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/icon/icon_bg.png"
  image_path_ios: "assets/icon/icon_ios.png"
  adaptive_icon_background: "#232323"
  adaptive_icon_foreground: "assets/icon/icon_bg.png"

# The following section is specific to Flutter.
flutter:
  generate: true
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Regular.ttf
          weight: 600
        - asset: fonts/OverpassMono-Light.ttf
          weight: 100
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 500
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
  assets:
    - assets/

  uses-material-design: true

scripts:
  codegen: dart run build_runner build --delete-conflicting-outputs
